server time.cloudflare.com iburst
server 0.cz.pool.ntp.org iburst
server 1.cz.pool.ntp.org iburst

driftfile /var/lib/chrony/drift
makestep 1.0 3
rtcsync
leapsectz right/UTC
logdir /var/log/chrony

allow 172.22.0.0/16
local stratum 8
