# Homelab – segmentovaná síť
# reservations.conf – VZOR (ukázka struktury; skutečný soubor je generovaný a obsahuje více záznamů)
# NEUPRAVOVAT RUČNĚ

# === VLAN42 (trusted) ===

host device-01 {
    hardware ethernet 00:00:5e:00:53:01;
    fixed-address 172.22.42.1;
    option host-name "device-01";
}

host device-02 {
    hardware ethernet 00:00:5e:00:53:02;
    fixed-address 172.22.42.2;
    option host-name "device-02";
}

# === VLAN60 (tabulky) ===

host display-01 {
    hardware ethernet 00:00:5e:00:53:03;
    fixed-address 172.22.60.11;
    option host-name "display-01";
}

host display-02 {
    hardware ethernet 00:00:5e:00:53:04;
    fixed-address 172.22.60.12;
    option host-name "display-02";
}

# === VLAN62 (ip telefony) ===

host phone-01 {
    hardware ethernet 00:00:5e:00:53:05;
    fixed-address 172.22.62.2;
    option host-name "phone-01";
}

# === VLAN99 (admin) ===

host adm01 {
    hardware ethernet 00:00:5e:00:53:06;
    fixed-address 172.22.99.9;
    option host-name "adm01";
}
