[global]
	winbind nested groups = yes
	winbind expand groups = 10
    netbios name = DATA
    workgroup = LAB
    realm = LAB.LAD
    security = ADS

    idmap config * : backend = tdb
    idmap config * : range = 3000-7999
    idmap config LAB : backend = rid
    idmap config LAB : range = 10000-999999

    winbind use default domain = yes
    winbind refresh tickets = yes
    winbind enum users = yes
    winbind enum groups = yes
    template shell = /bin/bash
    template homedir = /data/users/%U

    ntlm auth = ntlmv2-only
    host msdfs = no

    vfs objects = acl_xattr
    map acl inherit = yes
    store dos attributes = yes
    access based share enum = yes

    log file = /var/log/samba/log.%m
    max log size = 50

[homes]
    path = /data/users/%S
    browseable = yes
    read only = no
    create mask = 0700
    directory mask = 0700
    inherit acls = yes
    valid users = %S, @"LAB\domain admins"
    force user = %S
    force group = "domain admins"
    root preexec = /usr/bin/bash /data/user.sh %S

[data]
    path = /data/data
    read only = no
    browseable = yes
    guest ok = no
    inherit acls = yes
    directory mask = 2770
    create mask = 0660

[images]
    path = /data/images
    read only = no
    browseable = yes
    guest ok = no
    inherit acls = yes
    directory mask = 2770
    create mask = 0660
