# Global parameters
[global]
	dns forwarder = 172.22.21.1 172.22.21.2
	netbios name = DC1
	realm = LAB.LAD
	server role = active directory domain controller
	workgroup = LAB

[sysvol]
	path = /var/lib/samba/sysvol
	read only = No

[netlogon]
	path = /var/lib/samba/sysvol/lab.lad/scripts
	read only = No
